baseurl: "/"

markdown: kramdown
kramdown:
  math_engine: mathjax # can't be changed
  syntax_highlighter: rouge # can't be changed
  parse_block_html: true

sass:
  style: :compressed 
  sass_dir: assets/_scss

exclude:
  - README.md
  - .gitignore
  - generate_html
  - generate_pdf
  - drafts
  - src
  - labs/*/*.html
  
# theme: jekyll-theme-minimal

collections:
  labs:
    output: true


github: https://github.com/bacor/clc-labs