#!/bin/bash

dirname=$(dirname $0)
name=$1

if [ -d $dirname/labs/$name ]
then
    input="$dirname/labs/$name/$name.md"
    output="$dirname/labs/$name/$name.html"

elif [ -d $dirname/drafts/$name ]
then
    input="$dirname/drafts/$name/$name.md"
    output="$dirname/drafts/$name/$name.html"
else
    echo "Lab could not be found..."
fi

options="--number-sections --toc"
options="$options --filter pandoc-citeproc"
options="$options --katex"

if [ ! -f "$input" ]; then
    echo "File not found!"
else
    options="$options --template $dirname/src/template.html"
    pandoc $input -o $output $options
fi